#!/usr/bin/env node
/**
 * post_pr_comment.mjs
 * -------------------
 * Reads analysis_report.json and posts a formatted
 * Markdown summary as a GitHub PR comment via the REST API.
 */

import { readFileSync } from "fs";

// ─────────────────────────────────────────────
// CLI args
// ─────────────────────────────────────────────

function parseArgs() {
  const args = process.argv.slice(2);
  const get = (flag, def) => {
    const i = args.indexOf(flag);
    return i !== -1 && args[i + 1] ? args[i + 1] : def;
  };
  return {
    report: get("--report", "analysis_report.json"),
    prNumber: parseInt(get("--pr-number", "0"), 10),
    repo: get("--repo", ""),
  };
}

// ─────────────────────────────────────────────
// Formatting helpers
// ─────────────────────────────────────────────

const SEV_EMOJI = { critical: "🔴", high: "🟠", medium: "🟡", low: "🟢" };

function scoreBadge(score, target) {
  if (score >= target)          return `**${score}** ✅`;
  if (score >= target - 15)     return `**${score}** ⚠️`;
  return `**${score}** ❌`;
}

function buildComment(report, target) {
  const lines = ["## 📊 Code Quality Report — TEM / CQM / SAM", ""];

  if (report.summary?.skipped) {
    lines.push("_No JS/TS source files changed — analysis skipped._");
    return lines.join("\n");
  }

  const { all_pass: allPass, fixes_applied: fixesApplied } = report.summary ?? {};
  lines.push(`**Status:** ${allPass ? "✅ All files pass" : "❌ One or more files below target"}`);
  lines.push(`**Target score:** ${target}`, "");

  if (fixesApplied) {
    lines.push("> 🔧 **Auto-fix applied** — files were rewritten and committed automatically.", "");
  }

  for (const entry of report.files ?? []) {
    if (entry.error) {
      lines.push(`### ⚠️ \`${entry.filepath ?? "?"}\``, `_Error: ${entry.error}_`, "");
      continue;
    }

    const { analysis = {}, fix } = entry;
    const { scores = {}, filepath, issues = [], summary: fileSummary = "" } = analysis;
    const { tem = 0, cqm = 0, sam = 0, overall = 0 } = scores;

    lines.push(
      `### \`${filepath}\``, "",
      "| Metric | Score | Focus area |",
      "|--------|-------|------------|",
      `| TEM — Test Effectiveness | ${scoreBadge(tem, target)} | Coverage, testability, async isolation |`,
      `| CQM — Code Quality       | ${scoreBadge(cqm, target)} | var/let/const, async/await, error handling, naming |`,
      `| SAM — Software Agility   | ${scoreBadge(sam, target)} | Module boundaries, coupling, single responsibility |`,
      `| **Overall** (weighted)   | ${scoreBadge(overall, target)} | TEM×0.35 + CQM×0.40 + SAM×0.25 |`,
      ""
    );

    if (fileSummary) lines.push(`> ${fileSummary}`, "");

    if (issues.length) {
      lines.push("<details><summary>Issues found</summary>", "");
      for (const iss of issues) {
        const icon = SEV_EMOJI[iss.severity] ?? "•";
        const lineRef = iss.line ? ` (line ${iss.line})` : "";
        lines.push(
          `${icon} **[${iss.metric}] ${iss.title}**${lineRef}  `,
          `  ${iss.detail}  `
        );
        if (iss.suggestion) lines.push(`  _Suggestion: ${iss.suggestion}_`);
        lines.push("");
      }
      lines.push("</details>", "");
    }

    if (fix) {
      const fs = fix.scores ?? {};
      lines.push(
        "<details><summary>🔧 Auto-fix applied — changes made</summary>",
        "",
        `New scores — TEM: **${fs.tem}** | CQM: **${fs.cqm}** | SAM: **${fs.sam}**`,
        ""
      );
      for (const ch of fix.changes ?? []) lines.push(`- ${ch}`);
      lines.push("", "</details>", "");
    }

    lines.push("---");
  }

  lines.push("", "<sub>Generated by TEM/CQM/SAM GitHub Action · AWS Bedrock (Claude)</sub>");
  return lines.join("\n");
}

// ─────────────────────────────────────────────
// GitHub REST API helpers
// ─────────────────────────────────────────────

async function githubFetch(path, method = "GET", body = null) {
  const token = process.env.GITHUB_TOKEN;
  if (!token) throw new Error("GITHUB_TOKEN not set");

  const res = await fetch(`https://api.github.com${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
    body: body ? JSON.stringify(body) : undefined,
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GitHub API ${res.status}: ${text}`);
  }
  return res.json();
}

async function postPrComment(repo, prNumber, body) {
  // Delete any previous bot comment for this action
  const comments = await githubFetch(`/repos/${repo}/issues/${prNumber}/comments`);
  for (const c of comments) {
    if (c.user?.type === "Bot" && c.body?.includes("TEM / CQM / SAM")) {
      await githubFetch(`/repos/${repo}/issues/comments/${c.id}`, "DELETE");
      break;
    }
  }
  await githubFetch(`/repos/${repo}/issues/${prNumber}/comments`, "POST", { body });
  console.log("PR comment posted.");
}

// ─────────────────────────────────────────────
// Main
// ─────────────────────────────────────────────

async function main() {
  const args = parseArgs();
  if (!args.prNumber || !args.repo) {
    console.log("No PR number or repo — skipping comment.");
    return;
  }

  const report = JSON.parse(readFileSync(args.report, "utf-8"));
  const target = report.summary?.target_score ?? 80;
  const commentBody = buildComment(report, target);

  await postPrComment(args.repo, args.prNumber, commentBody);
}

main().catch((err) => {
  console.error("Failed to post PR comment:", err.message);
  process.exit(1);
});
